.Dd $Mdocdate: June 25 2018 $
.Dt NROFF-MAN 1
.Os
.Sh NAME
.Nm nroff-man
.Nd format manual pages
.Sh SYNOPSIS
.Nm
.Op Fl bi
.Op Fl I Cm os Ns = Ns Ar name
.Op Fl T Ar output
.Op Fl t Ar terminal
.Op Fl W Ar level
.Ar
.Sh DESCRIPTION
The
.Nm
utility formats manual pages for display.
It supports
.Xr nroff 1
\-man macros as well a subset of
.Xr nroff 1
commands.
.Pp
The following options are available:
.Bl -tag -width Ds
.It Fl b
Inhibit the bold font.
.It Fl i
Inhibit the italic font.
.It Fl I Cm os Ns = Ns Ar name
Provide the operating system name, if not provided by the
.Cm \.TH , \.AT ,
or
.Cm \.UC
macros.
.It Fl T Ar output
Select the output format.
Supported values for the
.Ar output
argument are
.Cm ascii ,
.Cm plain ,
and the default of
.Cm termcap .
.It Fl t Ar terminal
Overrides the terminal type specified in the environment with
.Ar terminal .
.It Fl W Ar level
Set the warning level.
Warning level 1 warns if unrecognized
.Xr nroff 1
commands are encountered.
Warning level 3 warns if non-standard GNU \-man macros are encountered.
.It Ar file
Read from the given input file.
If multiple files are specified, they are processed in the given order.
If unspecified,
.Nm
reads from standard input.
.El
.Ss Output
Output produced by
.Fl T Ar termcap
will use the termcap database for styling bold and italic text.
.Pp
Output produced by
.Fl T Ar ascii
will use the backspace characters to simulate bold and underline text.
.Pp
Output produced by
.Fl T Ar plain
will not style text.
.Sh ENVIRONMENT
The
.Ev TERM
environment variable affect the execution of
.Nm
as described in
.Xr environ 7 .
.Sh EXIT STATUS
.Ex -std
.Sh SEE ALSO
.Xr man 1 ,
.Xr nroff 1 ,
.Xr man 7
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
The
.Nm
utility was written by
.An -nosplit
.An Kelvin Sherlock Aq Mt ksherlock@gmail.com
.\" .Sh CAVEATS
.Sh BUGS
Not all
.Xr nroff 1
commands are implemented, or implemented correctly.
